import { Navigation } from "@/components/landing/navigation";
import { FooterSection } from "@/components/landing/footer-section";

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navigation />

      <main className="flex-1 pt-28 pb-20">
        <div className="container px-4 md:px-6 mx-auto max-w-4xl">
          <div className="space-y-6">
            <p className="text-sm font-mono text-muted-foreground">Last updated: March 14, 2026</p>
            <h1 className="text-4xl md:text-5xl font-display tracking-tight">Privacy Policy</h1>
            <p className="text-muted-foreground leading-relaxed">
              This Privacy Policy explains how Zenter ("we", "us", "our") collects, uses, discloses,
              and protects your personal information when you use our platform. We aim to comply with
              applicable data protection and consumer laws in Pakistan, including relevant provincial
              consumer protection laws and sectoral regulations where applicable.
            </p>
          </div>

          <div className="mt-10 space-y-10 text-sm leading-relaxed text-foreground/80">
            <section>
              <h2 className="text-2xl font-display mb-3">1. Information We Collect</h2>
              <p>
                We collect information you provide (such as name, email, profile details, and content),
                as well as information generated by your use of the platform (such as progress data and
                usage logs). If you choose to add links or upload media URLs, those details are stored
                in your profile.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">2. How We Use Information</h2>
              <p>
                We use your information to operate the platform, authenticate users, personalize your
                experience, provide learning and internship features, and improve our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">3. Legal Bases</h2>
              <p>
                We process data based on your consent, to fulfill our contract with you, to comply with
                legal obligations, and to pursue legitimate interests such as security and service
                improvement.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">4. Sharing and Disclosure</h2>
              <p>
                We may share information with service providers (e.g., hosting and analytics) only as
                necessary to operate the platform. We do not sell personal data. We may disclose
                information if required by law or to protect our legal rights.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">5. International Transfers</h2>
              <p>
                Some service providers may be located outside Pakistan. Where data is transferred,
                we take reasonable steps to ensure appropriate protections.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">6. Data Retention</h2>
              <p>
                We retain personal data only as long as needed for the purposes described or as required
                by law. You may request deletion of your account and associated data.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">7. Security</h2>
              <p>
                We implement reasonable technical and organizational measures to protect data, but no
                system is fully secure. Please keep your credentials confidential.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">8. Your Rights</h2>
              <p>
                Subject to applicable law, you may request access, correction, or deletion of your data.
                You may also withdraw consent for certain processing. Contact us using the details below.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">9. Children</h2>
              <p>
                Zenter is not intended for children under 13. If you are under 18, use the platform with
                consent from a parent or guardian.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">10. Changes</h2>
              <p>
                We may update this policy from time to time. Continued use of the platform after updates
                means you accept the revised policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-display mb-3">11. Contact</h2>
              <p>
                For privacy questions, contact us at <span className="font-mono">privacy@zenter.com</span>.
              </p>
            </section>
          </div>
        </div>
      </main>

      <FooterSection />
    </div>
  );
}

